services:
  db:
    image: postgres:latest
    container_name: postgres-DB
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3Gy5uwht4*
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend


  mcp:
    build: ./mcp
    container_name: mcp-server
    depends_on:
      - db
    env_file: .env
    ports:
      - "${MCP_PORT}:${MCP_PORT}"
    environment:
      -  DB_HOST=db  # le nom du service `db` dans le réseau Docker
      - MCP_PORT=${MCP_PORT}
    networks:
      - backend

networks:
  backend:
